"""adaptive_question_bank

Revision ID: 65dfe61824f7
Revises: e1b028348a17
Create Date: 2026-05-04 13:26:04.399886

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65dfe61824f7'
down_revision: str | None = 'e1b028348a17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptive_question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('theme_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_universal', sa.Integer(), nullable=True),
    sa.Column('is_universal', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adaptive_question_bank')
    # ### end Alembic commands ###
