"""task_029_survey_domain

Revision ID: d3703f31b9ee
Revises: 5a15d082726d
Create Date: 2026-05-05 13:56:59.974329

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3703f31b9ee'
down_revision: str | None = '5a15d082726d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_individual_share', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'archived')", name='surveys_status_check'),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_surveys_methodology_id'), 'surveys', ['methodology_id'], unique=False)
    op.create_index(op.f('ix_surveys_researcher_id'), 'surveys', ['researcher_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_survey_id'), 'invitations', ['survey_id'], unique=False)
    op.create_table('survey_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('respondent_anon_id', sa.Uuid(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_question_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='consent_pending', nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pinaba_image_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('consent_pending', 'in_progress', 'completed', 'abandoned')", name='survey_sessions_status_check'),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_sessions_survey_id'), 'survey_sessions', ['survey_id'], unique=False)
    op.create_table('pinaba_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False),
    sa.Column('public_uuid', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_uuid')
    )
    op.create_index(op.f('ix_pinaba_artifacts_session_id'), 'pinaba_artifacts', ['session_id'], unique=False)
    op.create_table('scale_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='scale_scores_confidence_range'),
    sa.CheckConstraint('value >= 0 AND value <= 100', name='scale_scores_value_range'),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_scores_session_id'), 'scale_scores', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scale_scores_session_id'), table_name='scale_scores')
    op.drop_table('scale_scores')
    op.drop_index(op.f('ix_pinaba_artifacts_session_id'), table_name='pinaba_artifacts')
    op.drop_table('pinaba_artifacts')
    op.drop_index(op.f('ix_survey_sessions_survey_id'), table_name='survey_sessions')
    op.drop_table('survey_sessions')
    op.drop_index(op.f('ix_invitations_survey_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_surveys_researcher_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_methodology_id'), table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###
