"""methodology_scale_question

Revision ID: e1b028348a17
Revises: e5a4b77dd748
Create Date: 2026-05-04 12:07:04.179787

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b028348a17'
down_revision: str | None = 'e5a4b77dd748'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='methodologies_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('theme_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_value', sa.Integer(), server_default='100', nullable=False),
    sa.Column('interpretation_low', sa.Text(), nullable=True),
    sa.Column('interpretation_mid', sa.Text(), nullable=True),
    sa.Column('interpretation_high', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_scales',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='question_scales_weight_range'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'scale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_scales')
    op.drop_table('scales')
    op.drop_table('questions')
    op.drop_table('methodologies')
    # ### end Alembic commands ###
