"""init

Revision ID: e5a4b77dd748
Revises: 
Create Date: 2026-04-27 21:05:33.455278

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e5a4b77dd748'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
